#!/bin/bash
# Azure Launcher - Command Reference
# This file shows all the commands to install, test, and run the application

echo "=========================================="
echo "Azure Launcher - Command Reference"
echo "=========================================="
echo ""

echo "1. INSTALLATION (One-Time Setup)"
echo "-------------------------------------------"
echo "# Install uv package manager"
echo "curl -LsSf https://astral.sh/uv/install.sh | sh"
echo "source ~/.bashrc"
echo ""
echo "# Create virtual environment"
echo "uv venv"
echo ""
echo "# Activate virtual environment"
echo "source .venv/bin/activate"
echo ""
echo "# Install the application"
echo "uv pip install -e ."
echo ""

echo "2. RUNNING THE APPLICATION"
echo "-------------------------------------------"
echo "# Activate environment (if not already active)"
echo "source .venv/bin/activate"
echo ""
echo "# Launch the mod manager"
echo "azure-launcher"
echo ""
echo "# Alternative: Run directly with Python"
echo "python -m mhw_mod_manager.app"
echo ""

echo "3. TESTING"
echo "-------------------------------------------"
echo "# Run all tests"
echo "pytest"
echo ""
echo "# Run tests with verbose output"
echo "pytest -v"
echo ""
echo "# Run tests with coverage"
echo "pytest --cov=mhw_mod_manager --cov-report=html"
echo ""
echo "# Run specific test file"
echo "pytest tests/test_mods.py -v"
echo ""

echo "4. DEVELOPMENT"
echo "-------------------------------------------"
echo "# Install development dependencies"
echo "uv pip install -e \".[dev]\""
echo ""
echo "# Type checking"
echo "mypy src/"
echo ""
echo "# Linting"
echo "ruff check src/"
echo ""
echo "# Auto-format code"
echo "ruff format src/"
echo ""

echo "5. QUICK TEST COMMANDS"
echo "-------------------------------------------"
echo "# Test that installation worked"
echo "which azure-launcher"
echo ""
echo "# Check Python version"
echo "python --version"
echo ""
echo "# List installed packages"
echo "uv pip list | grep mhw"
echo ""

echo "=========================================="
echo "To actually run these commands, copy and paste them individually"
echo "or source this file with: source RUN_COMMANDS.sh"
echo "=========================================="
